### ISSUE TITLE
TIMESTAMPS

### ISSUE THREAD

**Issue by m132** [chinatimmy/flask-webforum#12]
WE'RE IN AN URGENT NEED OF TIMESTAMPS
DON'T KEEP ME WAITING
MY AUTIZMO IS ABOUT TO REACH THE PEAK
NOTICE ME SENPIE

**Comment by ghost** [comment]
.time

    The time in Tel Aviv, Israel is 04:53:37 PM.

I got this

**Comment by ghost** [comment]
#15 is the first step forward, it was approved just now.

**Comment by ghost** [comment]
we should use a library to make time stamps local to the user

**Comment by chinatimmy** [comment]
pulling into scope
