### ISSUE TITLE
Text Input not big enough in mobile view SEE SCREENSHOT also the timestamps n shit

### ISSUE THREAD

**Issue by chinatimmy** [chinatimmy/flask-webforum#21]
![Capture](https://user-images.githubusercontent.com/66194071/84008200-063ffc80-a961-11ea-9fe0-f45f8601e4e8.PNG)

**Comment by ghost** [comment]
as the sole diversity engineer of this project I believe that writing "gay niggers" over and over again goes against our inclusiveness, as a matter of fact one of our friends is a gay nigger and I'm sure he would not like to see this image.

**Comment by chinatimmy** [comment]
sorry, i have autism i did not know this would offend anyone

**Comment by ghost** [comment]
> sorry, i have autism i did not know this would offend anyone

You are right, sorry if I came off as illsist, I do not hold anything against mentally ill people, they are normal and should be treated as such
