### ISSUE TITLE
Replies

### ISSUE THREAD

**Issue by chinatimmy** [chinatimmy/flask-webforum#5]
Yeah we need replies why not?!

**Comment by ghost** [comment]
true

**Comment by schattenpanzer** [comment]
the first step in doing that is to number the posts, you could probably use the primary key for that

**Comment by schattenpanzer** [comment]
Look!
```
sqlite> select * from posts;
id|content
1|coolbeans
2|pokemon
3|chillfruit
4|cereal
```
http://127.0.0.1:5000/@1/coffeebeans

this should be the way to reply, no?

**Comment by ghost** [comment]
the first step in doing that is to number the posts, you could probably use the primary key for that.

Look!
```
sqlite> select * from posts;
id|content
1|coolbeans
2|pokemon
3|chillfruit
4|cereal
```
http://127.0.0.1:5000/@1/coffeebeans

this should be the way to reply, no?

**Comment by ghost** [comment]
replies should be text only. we can make the view decide how to render replies but we don't need an extra column in the database for them
