### ISSUE TITLE
Limit DB and clear those posts

### ISSUE THREAD

**Issue by chinatimmy** [chinatimmy/flask-webforum#7]
We dont want bloated DB we want nice n small n cute
Clear posts past 1,500

**Comment by ghost** [comment]
or it could be every 500 posts

post 501 can delete post 1, post 502 can delete post 2, so on and so forth, to delete oldest post

if id >500: db....select * from posts sort by reverse numerical order, delete top row, something like that *cracks open sql book* mmm

**Comment by ghost** [comment]
hey girls, the db will clear posts that go over the limit of 500
